# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2


      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r22b
      #- run: echo "ANDROID_NDK_HOME=$ANDROID_NDK_LATEST_HOME" >> $GITHUB_ENV
      - run: sudo apt-get install zlib1g-dev
      - run: ldconfig -p | grep libpng
      #- working-directory: ./jni
      - name: Running NDK Build
        working-directory: ./tess-two/jni
        run: ndk-build
      - uses: actions/upload-artifact@v2
        with:
          name: libs
          path: tess-two/libs
